const { definePrompt } = require('cz-git')

module.exports = defineConfig({
  prompt: {
    useEmoji: true,
    allowCustomScopes: true,
    defaultScope: "api",
    defaultSubject: "describe the change",
    messages: {
      type: "Select the change type:",
      scope: "Select a scope for this change:",
      customScope: "Enter a custom scope:",
      subject: "Write a short imperative summary:",
      body: "Provide additional context if needed:",
      breaking: "List any breaking changes:",
      footerPrefixesSelect: "Select issue prefixes:",
      customFooterPrefix: "Enter a custom issue prefix:",
      footer: "List related issues, if any:",
      confirmCommit: "Confirm the commit message:",
    },
    types: [
      { value: "feat", name: "feat:     add a new feature", emoji: ":sparkles:" },
      { value: "fix", name: "fix:      fix a bug", emoji: ":bug:" },
      { value: "docs", name: "docs:     update documentation", emoji: ":memo:" },
      { value: "refactor", name: "refactor: improve code structure", emoji: ":recycle:" },
      { value: "test", name: "test:     add or update tests", emoji: ":white_check_mark:" },
      { value: "build", name: "build:    change build or dependencies", emoji: ":package:" },
      { value: "ci", name: "ci:       change CI or automation", emoji: ":construction_worker:" },
      { value: "chore", name: "chore:    maintenance work", emoji: ":wrench:" },
      { value: "perf", name: "perf:     improve performance", emoji: ":zap:" },
      { value: "revert", name: "revert:   revert a previous change", emoji: ":rewind:" },
    ],
    scopes: [
      "api",
      "bot",
      "worker",
      "cli",
      "config",
      "database",
      "events",
      "ffmpeg",
      "stream",
      "infra",
      "docs",
      "repo",
    ],
  },
});
